$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json

name: used-cars-train-env  # Provide the name for the environment
image: AzureML-sklearn-1.0-ubuntu20.04-py38-cpu
conda_file: ../../../data-science/environment/train-conda.yml
description: Environment created from a Docker image plus Conda environment to train Random Forest Regressor model # Provide the name for the environment